version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: whisp_socialmedia_postgres
    restart: always
    environment:
      POSTGRES_USER: whisp
      POSTGRES_PASSWORD: 5454
      POSTGRES_DB: whisp_database
    ports:
      - "5454:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: whisp_socialmedia_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres-data:
  redis-data:
